# Jekyll configuration

name: Sam Ervin's Blog
description: Now with more words!

# url is used for the RSS feed in feed.xml, as well as relative image paths
# (comment it out for local testing)
url: http://blog.samerv.in

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''

# This can be '' to hide the Github nav button
github: ''

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: ''

permalink: /:categories/:title
paginate: 5
paginate_path: "/:num/"

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

exclude: ['README.md', 'LICENSE']
